### ISSUE TITLE
just doesnt work (Apple : Think different)

### ISSUE THREAD

**Issue by nitani-x** [MiMillieuh/Illustrator-CC-2021-Linux#10]
nothing is downloaded nothing is installed

**Comment by MiMillieuh** [comment]
Very detailed issue...

I'm doing a maintenance on the server because of people trying to brutforce it...

**Comment by nitani-x** [comment]
I ♡u tho

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Micheal5311** [comment]
When will it be back up? I kinda need to use it before tomorrow

**Comment by MiMillieuh** [comment]
> When will it be back up? I kinda need to use it before tomorrow

I'm uploading back things, Please be patient it should be done in less than an hour

**Comment by nitani-x** [comment]
Your a cool guy

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MiMillieuh** [comment]
Needed files for Illustrator should be up, download may be slow due to the backup still going on.
