### ISSUE TITLE
Can you reupload?

### ISSUE THREAD

**Issue by LastEmperor0** [MiMillieuh/Illustrator-CC-2021-Linux#7]
Can you reupload?

**Comment by LastEmperor0** [comment]
BTW i can install all of them by manually

**Comment by MiMillieuh** [comment]
What's the issue ?

**Comment by LastEmperor0** [comment]
There is no problem, you wrote Server are down in the readme section. But looks like it is fixed.

**Comment by MiMillieuh** [comment]
I mentioned this because someone is literally trying to brutforce my server but I fixed the issue and forgot to remove that
